[[section-introduction-and-goals]]
== Introduction and Goals

A decentralized web application of routes will be made following the SOLID architecture and the React framework. With it, users will be able to store routes, visualize them on a map and share photos, videos or other types of files with their friends or groups of friends.


=== Requirements Overview

==== Functionals

- Users should be able to view the routes on a map and store them on their own pods.
- By using their own pods, the information will be totally decentralized, favoring data security.
- They will also be able to have friends and groups of friends with whom to share these routes, photos, videos, etc.


==== Non functionals

- The system must be accessible and intuitive for all types of users, although special attention will be focused on favouring those with less experience in applications of this style.
- Avoid compromising user information by decentralizing data on separate pods for each user.
- Follow the recommendations of the W3C to ensure an error-free and safer website.


=== Quality Goals

.Table Goals
|===
|Goal|Description
|Mainteinability|The website can be easily maintained and progressively expanded in a simple way as development progresses, either by extending existing features or by adding new ones.
|Performance|The system must be effective and react quickly to user requests for action.
|Privacy|User data should be stored out of the internal servers and protected to prevent third parties from accessing them.
|Testability|Tests must be able to be carried out to check the correct functioning of the system.
|Usability|The application must be intuitive and easy to use by any type of user.
|===



=== Stakeholders


.Table Stakeholders
[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Application users | _These represent the end users of the application_ | _Have at their disposal an application that allows them to store their routes and share them with their friends._
| Teachers | _Who evaluate the project being carried out_ | _Find a project that meets the above requirements._
| Developers| _Who will be in charge of developing the product_ | _Make a system that meets the requirements above._
|===


