[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Se realizará una aplicación web descentralizada de rutas siguiendo las especificaciones SOLID.	Los usuarios podrán almacenar rutas,visualizarlas en un mapa y podrán compartir fotos, vídeos u otro tipo de ficheros con  amigos.
****

=== Requirements Overview


==== Funcionales
[role="arc42help"]
****
- La aplicación se basará en una arquitectura descentralizada en la que los datos están separados de la aplicación
- Los deberán poder visualizar las rutas en un mapa y almacenarlas en sus propiods pods. Además, se podrá tener amigos y grupos de amigos con quien compartir las rutas,fotos,vídeos,etc. 
****

=== No funcionales
[role="arc42help"]
****
- El sistema deberá ser accesible e intuituvo para todo tipo de usuario, especialmente el novato.
- Evitar comprometer la información de los usuarios descentralizando los datos.
- Seguir las recomendaciones del w3c.
****

=== Quality Goals

[role="arc42help"]
****
.Table Goals
[options="header",cols="2"]
|===
|Goal|Description
|Accesibilidad|
|Disponibilidad|
|Interoperabilidad|
|Seguridad|
|Testeabilidad|
|Escalabilidad|
|Consistencia|
|Usabilidad|
|Modularidad|
|===

****

=== Stakeholders

[role="arc42help"]
****
.Table Stakeholders
[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Usuarios de la aplicación | _<Contact-1>_ | _<Expectation-1>_
| Profesores | _<Contact-2>_ | _<Expectation-2>_
| Desarrolladores | _<Contact-2>_ | _<Expectation-2>_
|===
****


