[[section-concepts]]
== Cross-cutting Concepts

=== _Domain Concepts_

_i.e domain models, business data model_

=== _User Experience concepts (UX)_

_User interface_

_Ergonomics_

_Internationalization_ 

How to make the system usable in international settings, translation, screen-layout, wording and other

=== _Safety and security concepts_

_Security_

i.e. how to achieve confidentiality, non-reputiability and other goals.

_Safety_

Safety-critical systems are those whose failure or malfunction may result in death or injury or severe financial loss

=== _Architecture and design patterns_	

recurring patterns within the system 

=== _“Under-the-hood” concepts_

_Persistency_

how / where to store and retrieve data

_Process control_	


_Transaction handling_

How to handle technical or business transactions, i.e. to achieve ACID properties

_Session handling_

How to handle user/client sessions

_Communication and integration_

How to integrate with other systems, how to communicate (i.e. sync, async, pub-sub…)

_Exception and error handling_

What errors to handle, how to handle exceptional situations

_Parallization and threading_

How to parallelize tasks, how to create/spawn/manage processes

_Plausibility checks and validation_

i.e. client-side validation, how to verify/check data, input, results.

_Business rules_

i.e. how to use a rule-engine, how to implement/configure business rules, how to change those…

_Batch processing_

How to process data in batches (i.e. offline processing)

_Reporting_

How to create reports, how to gather the required data, how to render the results

=== _Development concepts_	

_Build, test, deploy_

_Code generation_	

_Migration_

_Configurability_

=== _Operational concepts_	

_Administration_

_Management_

_Disaster-Recovery_ 
 	
_Scaling_	 

_Clustering_

_Monitoring, Logging_	 

_High Availability_	 

_Load balancing_
